# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:       [with_toc_data]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Scrambled Eggs
tagline:          'Ramblings and unramblings'
description:      'Ramblings and unramblings'
url:              http://scrambledeggsontoast.github.io

author:
  name:           'Josh Kirklin'
  url:            https://github.com/ScrambledEggsOnToast

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ScrambledEggsOnToast/scrambledeggsontoast.github.io

defaults:
    scope:
        path: ""
    values:
        toc: false
